$rosewater = rgb(c0caf5)
$rosewaterAlpha = c0caf5
$flamingo = rgb(f7768e)
$flamingoAlpha = f7768e
$pink = rgb(bb9af7)
$pinkAlpha = bb9af7
$mauve = rgb(bb9af7)
$mauveAlpha = bb9af7
$red = rgb(f7768e)
$redAlpha = f7768e
$maroon = rgb(ff9e64)
$maroonAlpha = ff9e64
$peach = rgb(ff9e64)
$peachAlpha = ff9e64
$yellow = rgb(e0af68)
$yellowAlpha = e0af68
$green = rgb(9ece6a)
$greenAlpha = 9ece6a
$teal = rgb(7dcfff)
$tealAlpha = 7dcfff
$sky = rgb(7dcfff)
$skyAlpha = 7dcfff
$sapphire = rgb(7aa2f7)
$sapphireAlpha = 7aa2f7
$blue = rgb(7aa2f7)
$blueAlpha = 7aa2f7
$lavender = rgb(c0caf5)
$lavenderAlpha = c0caf5

$text = rgb(c0caf5)
$textAlpha = c0caf5
$subtext1 = rgb(a9b1d6)
$subtext1Alpha = a9b1d6
$subtext0 = rgb(9aa5ce)
$subtext0Alpha = 9aa5ce

$overlay2 = rgb(565f89)
$overlay2Alpha = 565f89
$overlay1 = rgb(414868)
$overlay1Alpha = 414868
$overlay0 = rgb(363b54)
$overlay0Alpha = 363b54

$surface2 = rgb(2f334d)
$surface2Alpha = 2f334d
$surface1 = rgb(24283b)
$surface1Alpha = 24283b
$surface0 = rgb(1f2335)
$surface0Alpha = 1f2335

$base = rgb(1a1b26)
$baseAlpha = 1a1b26
$mantle = rgb(16161e)
$mantleAlpha = 16161e
$crust = rgb(0f0f14)
$crustAlpha = 0f0f14
